version: "3.9"
services:
  nginx:
    image: nginx:latest
#    containter_name: hugo_test_compose
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/mironov/letsencrypt/:/etc/letsencrypt/
      - /var/log/nginx/log/:/var/log/nginx/log/
#      - www/hugo:/var/www/hugo/   Those pushed by Jenkins.
#      - sites-available/default:/etc/nginx/sites-available/default
#      - nginx.conf:/etc/nginx/nginx.conf
